apiVersion: nfd.openshift.io/v1alpha1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-master-server 
  namespace: openshift-nfd-operator
spec:
  namespace: openshift-nfd
  image: quay.io/zvonkok/node-feature-discovery:v4.2
